# Generated by Django 6.0.4 on 2026-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
    ]
